package org.apache.uima.ducc.cli;

public interface IDuccCallback
{
    /**
     * This method is called by relevent parts of the API with messages generated by DUCC, 
     * including console messages generated by ducc_ling, prior to it exec-ing into
     * it's process.
     *
     * @param host If not null, the name of the host that generated the message.  This may
     *             be null, indicating the host isn't known or is not relevent.
     *
     * @param filename If not null, the name of the log where this message would have been
     *             logged if the console were not redirected to the API.
     *
     * @param msg This is the logged message.
     */
    public void duccout(String host, String filename, String msg);


    /**
     * This method is called by relevent parts of the API with messages redirected
     * from the remote process.  
     *
     * @param host If not null, the name of the host that generated the message.  This may
     *             be null, indicating the host isn't known or is not relevent.
     *
     * @param filename If not null, the name of the log where this message would have been
     *             logged if the console were not redirected to the API.
     *
     * @param msg This is the logged message.
     */
    public void consout(String host, String filename, String msg);
}
