package org.apache.uima.ducc.cli;

public interface IDuccCallback
{
    /**
     * This method is called by relevant parts of the API with messages generated by DUCC, 
     * including console messages generated by ducc_ling, prior to it exec-ing into
     * it's process.
     *
     * @param msg This is the logged message.
     */
    public void duccout(String msg);


    /**
     * This method is called by relevant parts of the API with messages redirected
     * from the remote process.  
     *
     * @param msg This is the logged message.
     */
    public void consout(String msg);
    
    /**
     * This method is called when the name of the host generating the messages is known.
     *
     * @param name The name of the host that generated the message.  
     */
    public void host(String name);
    
    /**
     * This method is called with the name of the logfile that would have been written 
     * if the console had not been redirected to the consout method.
     * It is not called if the console is not redirected.
     *
     * @param name The name of the logfile that would have been created.
     */
    public void logfile(String name);
}
