#!/usr/bin/env python
# -----------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# -----------------------------------------------------------------------
import sys
import getpass

from ducc_util import DuccUtil
from ducc_base import DuccProperties

class PamTest(DuccUtil):
    def main(self, argv):
        user = raw_input("User: ")
        pw = getpass.getpass()
        service = 'org.apache.uima.ducc.ws.authentication.PamTest'
        cmd = []
        cmd.append(self.java())
        cmd.append(service)
        cmd.append(user)
        cmd.append(pw)
        pid = self.spawn(' '.join(cmd))
        return pid
        
if __name__ == "__main__":
    pamtest = PamTest()
    pamtest.main(sys.argv[1:])
