#! /usr/bin/env python

import os
import sys

class Patches():
        
    def __init__(self):
        pass
    
    def run(self):
        file_home = os.path.dirname(os.path.realpath(sys.argv[0]))
        ducc_home = file_home.rsplit('/',3)[0]
        #
        file = 'ducc.py'
        src = ducc_home+'/examples/uima-ducc-vm/config/patches/admin/'+file
        tgt = ducc_home+'/admin/'+file
        orig = ducc_home+'/admin/'+file+'.orig'
        command = 'cp -p'+' '+tgt+' '+orig
        os.system(command)
        print 'saved: '+orig
        command = 'cp -p'+' '+src+' '+tgt
        os.system(command)
        print 'installed: '+tgt
                
if __name__ == '__main__':

    function = Patches()
    function.run()
