#! /usr/bin/env python

import os
import sys

class Prep():
        
    def __init__(self):
        pass
    
    def run(self):
        file_home = os.path.dirname(os.path.realpath(sys.argv[0]))
        ducc_home = file_home.rsplit('/',3)[0]
        #
        script = ducc_home+'/examples/systemtest/reg_service'
        for i in range(1,6):
            service = str(i)
            command = script+' '+'-i'+' '+service
            os.system(command)
            print 'registered service: '+service
        
        service = str(1)
        script = ducc_home+'/bin/ducc_services'
        command = script+' '+'--autostart'+' '+'true'+' '+'--modify'+' '+service
        os.system(command)
        print 'autostart service: '+service
        
if __name__ == '__main__':

    function = Prep()
    function.run()
