#! /usr/bin/env python

# -----------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# -----------------------------------------------------------------------


import sys
from ducc_base import DuccBase

class DuccProcessSubmit(DuccBase):

    def main(self, argv):
        self.spawn(self.java(), '-cp', self.DUCC_HOME + '/lib/uima-ducc-cli.jar', 'org.apache.uima.ducc.cli.DuccManagedReservationSubmit', ' '.join(self.mkargs(argv)))

if __name__ == "__main__":
    submit = DuccProcessSubmit()
    #for i in os.environ['CLASSPATH'].split(':'):
    #    print i

    submit.main(sys.argv[1:])
