#! /usr/bin/env python

# -----------------------------------------------------------------------
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
# -----------------------------------------------------------------------


from ducc_boot import *
import getopt

set_ducc_home()

from ducc_util import DuccUtil

class DuccWeb(DuccUtil):

    def syntax(self):
        print "  --qm or --query-machines";
        print "  --qr or --query-reservations";
        
    def main(self, argv):
        if ( len(argv) > 0 ):
            if ( argv[0] == '--qm' or argv[0] == '--query-machines'):
                self.spawn(self.java(), '-jar', self.DUCC_HOME + '/lib/ducc-web-query-machines.jar', ' '.join(argv[1:]))
                return
            if ( argv[0] == '--qr' or argv[0] == '--query-reservations' ):
                self.spawn(self.java(), '-jar', self.DUCC_HOME + '/lib/ducc-web-query-reservations.jar', ' '.join(argv[1:]))
                return
            self.syntax();
        else:
            self.syntax();

if __name__ == "__main__":
    svc = DuccWeb()
    svc.main(sys.argv[1:])

